/* Generated by build-requires.cjs. Do not edit directly.
 * Sources: facades/TLBuilder.js
 */

/* facades/TLBuilder.js */
/* TLBuilderの安定した公開API。 */
(function(root){
	'use strict';
	const versions = root.TLBuilderVersions ||= {};
	const defaultVersion = '2026-09-17';
	function TLBuilder(options = {}){
		const version = options.uiVersion || defaultVersion;
		const build = versions[version];
		if(typeof build !== 'function')throw new RangeError(`TLBuilder version ${version} is not loaded.`);
		return build(options);
	}
	Object.defineProperty(TLBuilder, 'versions', {get: () => Object.freeze(Object.keys(versions))});
	TLBuilder.parseResponse = (response, version = defaultVersion) => {
		const parse = versions[version]?.parseResponse;
		if(typeof parse !== 'function')throw new RangeError(`TLBuilder version ${version} is not loaded.`);
		return parse(response);
	};
	TLBuilder.registerVersion = (version, build) => {
		if(!/^\d{4}-\d{2}-\d{2}$/.test(version) || typeof build !== 'function')throw new TypeError('A dated version and builder function are required.');
		versions[version] = build;return TLBuilder;
	};
	root.TLBuilder = TLBuilder;
})(globalThis);
