/* Generated by build-requires.cjs. Do not edit directly.
 * Sources: facades/TweetElementBuilder.js
 */

/* facades/TweetElementBuilder.js */
/* 安定した公開API。実装は先に読み込んだTEB-v*.jsから選ぶ。 */
(function(root){
	'use strict';
	const versions = root.TweetElementBuilderVersions ||= {};
	const defaultVersion = '2026-09-17';
	function selected(version){
		const build = versions[version];
		if(typeof build !== 'function')throw new RangeError(`TweetElementBuilder version ${version} is not loaded.`);
		return build;
	}
	function TweetElementBuilder(tweetData, options = {}){
		return selected(options.uiVersion || defaultVersion)(tweetData, options);
	}
	Object.defineProperties(TweetElementBuilder, {
		versions: {get: () => Object.freeze(Object.keys(versions))},
		normalize: {get: () => selected(defaultVersion).normalize},
		detectTheme: {get: () => selected(defaultVersion).detectTheme},
		themes: {get: () => selected(defaultVersion).themes},
		i18n: {get: () => root.builderI18n},
	});
	TweetElementBuilder.loadTextData = options => root.builderI18n.load(options);
	TweetElementBuilder.registerVersion = (version, build) => {
		if(!/^\d{4}-\d{2}-\d{2}$/.test(version) || typeof build !== 'function')throw new TypeError('A dated version and builder function are required.');
		versions[version] = build;
		return TweetElementBuilder;
	};
	root.TweetElementBuilder = root.tweetElementBuilder = TweetElementBuilder;
})(globalThis);

